### ISSUE TITLE
Number of Images and groundtruth mask

### ISSUE THREAD

**Issue by AKASH2907** [namtpham/casia2groundtruth#1]
The number of images in Tampered folder is 5125 whereas the number of mask images are 5079. Why that so?
How you have generated masks. There are so many irregualrities in the files present in masks directory and files present in Tampered folder. So many ground truth mask doesn't exist.

**Comment by gtwell** [comment]
I also want to know. And how did you make the groundtruth? I want to make casia1 dataset too.

**Comment by namtpham** [comment]
Hello,
I am sorry for the late reply. The masks were generated by simply subtracting the tampered images and their corresponding authentic images. Since there are noises in the images, I did some post-processing operations for the ground truth images. 
The number of mask images are fewer than the number of tampered images because the owners of this dataset wrongly named the files.
I will update the code and the new update of this ground truth dataset soon. Most of the irregularities in the previous version are well handled.

**Comment by gyheart** [comment]
Is the new ground truth available now? Thanks.
